### PR TITLE
Fixed fork() cloning unwanted file descriptors

### PR DESCRIPTION
**Pull request by TobiasFaller**

### CODE REVIEW

**Comment by arminbiere** [comment]
Well, 'closeffrom' does not exist in 'Darwin' out of the box (it seems to be BSD and GNU specific).

Preliminary search also did not give me a replacement.

```
biere@ccamacmini01 cadical % make
/Library/Developer/CommandLineTools/usr/bin/make -C "/Users/biere/src/cadical/build"
g++ -Wall -Wextra -g -std=c++11 -I../build -I../src -c ../src/file.cpp
../scripts/make-build-header.sh > build.hpp
g++ -Wall -Wextra -g -std=c++11 -I../build -I../src -c ../src/version.cpp
../src/file.cpp:303:7: error: no member named 'closefrom' in the global namespace
    ::closefrom (3);
    ~~^
1 error generated.
make[1]: *** [file.o] Error 1
make: *** [all] Error 2
```

Further I do not get completely, why the original problem happens, and why this fix
solves it (lets the test case go through).  Back to the white board I think.

**Comment by krobelus** [comment]
I think a portable and simple way of avoiding lingering file descriptors in children is to add the `FD_CLOEXEC` flag via `fcntl`.
That means at least

```diff
-out = ::open (path, O_CREAT | O_TRUNC | O_WRONLY, 0644)
+out = ::open (path, O_CREAT | O_TRUNC | O_WRONLY | O_CLOEXEC, 0644)
```

and similar for all other files that might be open at this time.

It's probably possible to get by without closing files properly and use `fsync()` instead but that's ugly

**Comment by TobiasFaller** [comment]
But this will not inhibit the cloning of the FDs of other active pipes of other threads from the parent process, right?
Because this is the reason for hanging / waiting child processes in my perspective.

**Comment by TobiasFaller** [comment]
Also, isn't the FD required in the child process to write to the output file?
Wouldn't `O_CLOEXEC` result in the file descriptor not being available anymore after the `execv` call?

**Comment by krobelus** [comment]
> But this will not inhibit the cloning of the FDs of other active pipes of other threads from the parent process, right?

yes, those need to set `CLOEXEC` too

> Also, isn't the FD required in the child process to write to the output file?
> Wouldn't O_CLOEXEC result in the file descriptor not being available anymore after the execv call?

yes but one fd is enough. The code already does

	int tmp = dup2 (out, 1);

which sets 1 to refer to the same stream as `out`.

From `close(2)`:

```
If  fd  is  the last file descriptor referring to the underlying open file description
(see open(2)), the resources associated with the open file description are  freed;
```

so a `fd` is just a reference to a reference counted stream (like `std::shared_ptr`).

**Comment by TobiasFaller** [comment]
Yes, thank you very much. The original solution would have been to implement an own version of `closefrom` on Darwin. But letting `execv` clean up all the non-required handles is a lot cleaner. I'll implement and test the solution later.

**Comment by krobelus** [comment]
Yeah `dup3` and `pipe2` would automatically set `O_CLOEXEC` but they're not yet portable.

> So probably fcntl has to be used instead after the dup2() call.

CLOEXEC will only close on exec, so the forked child may close/redirect fds before it calls exec.

If you do this a lot (there are 69 matches for `close \(` you should maybe write [wrappers that close automatically](https://github.com/fish-shell/fish-shell/blob/LastC%2B%2B11/src/fds.cpp#L255-L285)

**Comment by arminbiere** [comment]
> I think a portable and simple way of avoiding lingering file descriptors in children is to add the `FD_CLOEXEC` flag via `fcntl`. That means at least
> 
> ```diff
> -out = ::open (path, O_CREAT | O_TRUNC | O_WRONLY, 0644)
> +out = ::open (path, O_CREAT | O_TRUNC | O_WRONLY | O_CLOEXEC, 0644)
> ```
> 
> and similar for all other files that might be open at this time.
> 
> It's probably possible to get by without closing files properly and use `fsync()` instead but that's ugly

We looked at this but then were not sure it would work.  It was further unclear to use, whether the '::open' should be in the child or in the parent.

**Comment by arminbiere** [comment]
> Well, 'closeffrom' does not exist in 'Darwin' out of the box (it seems to be BSD and GNU specific).
> 
> Preliminary search also did not give me a replacement.
> 
> ```
> biere@ccamacmini01 cadical % make
> /Library/Developer/CommandLineTools/usr/bin/make -C "/Users/biere/src/cadical/build"
> g++ -Wall -Wextra -g -std=c++11 -I../build -I../src -c ../src/file.cpp
> ../scripts/make-build-header.sh > build.hpp
> g++ -Wall -Wextra -g -std=c++11 -I../build -I../src -c ../src/version.cpp
> ../src/file.cpp:303:7: error: no member named 'closefrom' in the global namespace
>     ::closefrom (3);
>     ~~^
> 1 error generated.
> make[1]: *** [file.o] Error 1
> make: *** [all] Error 2
> ```
> 
> Further I do not get completely, why the original problem happens, and why this fix solves it (lets the test case go through). Back to the white board I think.


Our current understanding after some white-board discussion of what is happening is that the order in which the copied file-descriptors in child processes are closed could become cyclic (actually with the test case on this branch it is deterministically cyclic it seems).  So multiple child processes (the 'gzip' for instance called through 'exec') wait cyclically on closing their input.

**Comment by krobelus** [comment]
The test works if I add a mutex

```diff
diff --git a/src/file.cpp b/src/file.cpp
index 825bc25..053ce85 100644
--- a/src/file.cpp
+++ b/src/file.cpp
@@ -1,4 +1,5 @@
 #include "internal.hpp"
+#include <mutex>
 
 /*------------------------------------------------------------------------*/
 
@@ -257,6 +258,8 @@ FILE *File::read_pipe (Internal *internal, const char *fmt, const int *sig,
 
 #ifndef _WIN32
 
+static std::mutex FD_MUTEX;
+
 FILE *File::write_pipe (Internal *internal, const char *command,
                         const char *path, int &child_pid) {
   assert (command[0] && command[0] != ' ');
@@ -272,6 +275,9 @@ FILE *File::write_pipe (Internal *internal, const char *command,
   char *absolute_command_path = find_program (argv[0]);
   int pipe_fds[2], out;
   FILE *res = 0;
+
+  std::lock_guard lock{FD_MUTEX};
+
   if (!absolute_command_path)
     MSG ("could not find '%s' in 'PATH' environment variable", argv[0]);
   else if (pipe (pipe_fds) < 0)
```

So there must be some race in this region.

The gzip processes are hanging in `read()` even though we are closing their stdin.
I think what happens is that `fork()` will copy any `out` that are open in concurrent threads.
Those file descriptors are distinct from `out` in the forking thread, so they will never get closed.
It's possible that there is a lock-free solution but since `fork()` reads global state (it copies all open file descriptors), a mutex seems appropriate.

**Comment by arminbiere** [comment]
We also experimented with locking (actually serializing the writing which worked but not really what we want).  So you do not buy in my proposed reason of circular waiting?

**Comment by krobelus** [comment]
I haven't looked at any traces that could show circular waiting 
because the scenario where it hangs is even simpler.

Below program reproduces the hang on my system on around every other
run. Increasing N increases the chance of hitting the hang.

Uncommenting the `FD_CLOEXEC` lines makes it kinda work because every forked
child eventually exec's, closing all such cloned fds. I believe there's
still a race if fork() happens just before fcntl() which is probably why
`pipe2` was invented.

> It was further unclear to us, whether the '::open' should be in the child or in the parent.

Both would work but it's safer and easier to add error handling if the
parent opens it.  The code between fork and exec should be async-signal safe,
so it can't allocate memory etc.

```c
#include <assert.h>
#include <cstdio>
#include <cstring>
#include <fcntl.h>
#include <memory>
#include <pthread.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

void *start (void *i_) {
  int thread_index = (size_t) i_;
  int pipefds[2];
  assert (pipe (pipefds) == 0);
  int read_end = pipefds[0], write_end = pipefds[1];

  // fcntl (read_end, F_SETFD, FD_CLOEXEC);
  // fcntl (write_end, F_SETFD, FD_CLOEXEC);

  int child_pid = fork ();
  assert (child_pid >= 0);
  if (!child_pid) {
    close (write_end); // not necessary with CLOEXEC
    close (0);
    dup (read_end);
    close (read_end); // not necessary with CLOEXEC
    execl ("/bin/cat", "/bin/cat");
    assert (false);
  }
  close (read_end);
  char tmp[50];
  sprintf (tmp, "thread %lu spawned child %d...\n", thread_index,
           child_pid);
  write (write_end, tmp, strlen (tmp));
  usleep (1000);
  close (write_end);
  int wstatus;
  waitpid (child_pid, &wstatus, 0);
  return nullptr;
}

int main () {
  constexpr size_t N = 2;
  pthread_t threads[N];
  for (size_t i = 0; i < N; i++)
    pthread_create (&threads[i], nullptr, start, (void *) i);
  for (size_t i = 0; i < N; i++)
    pthread_join (threads[i], nullptr);
}
```

**Comment by TobiasFaller** [comment]
> I haven't looked at any traces that could show circular waiting because the scenario where it hangs is even simpler.

The program you provided demonstrates exactly the circular waiting problem discussed. Below is an example trace:

1) Pipe 1 is created in thread T1 with writing FD1 and reading FD2 file descriptor
2) Pipe 2 is created in thread T2 with writing FD3 and reading FD4 file descriptor
3) Thread T1 forks into process P2 and receives 4 pipe file descriptors (FD1-FD4)
4) Thread T2 forks and process P3 and receives 4 pipe file descriptors (FD1-FD4)
5) Process P2 closes the writing file descriptor FD1
6) Process P3 closes the writing file descriptor FD3
7) Process P2 calls exec and cat takes over with FD2, FD3, FD4
8) Process P3 calls exec and cat takes over with FD1, FD2, FD4
9) In process P2 cat waits for all copies of FD1 to be closed to receive an EOF event but P3 has a copy
10) In process P3 cat waits for all copies of FD3 to be closed to receive an EOF event but P2 has a copy
11) Process P1 (parent) closes its copies of FD1, FD2, FD3, FD4
12) Process P2 and P3 wait for each other indefinitely

Sadly, specifying `O_CLOEXEC` for the pipes requires `pipe2` which is not available on Darwin.
Using `fcntl` decreases the time window of copying the FDs without the `FD_CLOEXEC` attribute, but doesn't fully inhibit it.
Instead of using `FD_CLOEXEC` we implemented `closefrom` for Darwin instead (see **https://github.com/arminbiere/cadical/pull/121**), which doesn't exhibit the race condition problem.
`closefrom` is in this case used to close accidentally cloned file descriptors (FD3 and FD4 in P2, and FD1 and FD2 in P3).

**Comment by krobelus** [comment]
That's correct, but even without circular fd-dependencies,
a single leaked fd is enough to make things go awry.
If P3 is no `cat` but `sleep 1.5` without piped input,
P2 `cat` will still only finish after P3 has exited because its stdin pipe is kept alive.

> Using fcntl decreases the time window of copying the FDs without the FD_CLOEXEC attribute, but doesn't fully inhibit it.

yeah that would need a mutex around `pipe()` and `fcntl()` on macOS

```diff
--- test.cpp	2024-11-01 00:26:15.396769578 +0100
+++ test.cpp	2024-11-01 00:26:51.290103483 +0100
 void *start (void *i_) {
   int thread_index = (size_t) i_;
+  if (thread_index == 1) {
+    int child_pid = fork ();
+    assert (child_pid >= 0);
+    if (!child_pid) {
+      execl ("/bin/sleep", "/bin/sleep", "1.5", nullptr);
+      assert (false);
+    }
+    int wstatus;
+    waitpid (child_pid, &wstatus, 0);
+    printf ("sleep finished\n");
+    return nullptr;
+  }
   int pipefds[2];
   assert (pipe (pipefds) == 0);
   int read_end = pipefds[0], write_end = pipefds[1];
@@ -36,6 +49,7 @@
   close (write_end);
   int wstatus;
   waitpid (child_pid, &wstatus, 0);
+  printf ("cat finished\n");
   return nullptr;
 }
```

**Pull request merged**
